version: "3.9"
services:
    web:
        env_file:
            - .env
        image: nginx
        container_name: load-balancer
        volumes:
            - ./docker/conf/nginx/load-balancer.conf:/etc/nginx/nginx.conf
            - ./docker/volumes/log/lb:/var/log/nginx
        ports:
            - ${LOAD_BALANCER_PORT}:80
        restart: unless-stopped
        depends_on:
            - node1
            - node2
        networks:
            - lb-net
    node1:
        env_file:
            - .env
        image: nginx
        container_name: lb-nginx1
        volumes:
            - ./docker/conf/nginx/node1/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/volumes/log/node1-nginx:/var/log/nginx
            - ./docker/volumes/app:/var/www/html
        ports:
            - ${NGINX1_PORT}:80
        restart: unless-stopped
        depends_on:
            - php1
        networks:
            - lb-net
    node2:
        env_file:
            - .env
        image: nginx
        container_name: lb-nginx2
        volumes:
            - ./docker/conf/nginx/node1/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/volumes/log/node2-nginx:/var/log/nginx
            - ./docker/volumes/app:/var/www/html
        ports:
            - ${NGINX2_PORT}:80
        restart: unless-stopped
        depends_on:
            - php2
        networks:
            - lb-net
    php1:
        build: docker/php8.0-nginx
        container_name: lb-php1
        restart: unless-stopped
        depends_on:
            - redis
            - database
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/volumes/app:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - lb-net
    php2:
        build: docker/php8.0-nginx
        container_name: lb-php2
        restart: unless-stopped
        depends_on:
            - redis
            - database
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/volumes/app:/var/www/html
        ports:
            - "9001:9000"
        networks:
            - lb-net
    redis:
        image: redis/redis-stack
        container_name: lb-redis
        volumes:
            - ./docker/volumes/redis-data/:/data
        ports:
            - ${REDIS_PORT}:6379
            - ${REDISINSIGHT_PORT}:8001
        networks:
            - lb-net
    database:
        env_file:
            - .env
        image: mysql:8.0
        container_name: lb-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/conf/mysql/initdb:/docker-entrypoint-initdb.d
            - ./docker/volumes/backups:/backups
            - ./docker/volumes/wwwdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - lb-net
networks:
    lb-net:
        name: lb-network
